name: test-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
  pull_request:
    branches:
      - main
jobs:
  print-hello:
    runs-on: ${{ matrix.os }}
    steps:
      - run: ::debug::Hello World
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - run: dotnet restore
      - run: dotnet build
  test: 
    runs-on: ${{ matrix.os }}
    steps:
      - run: dotnet test
  publish: 
    runs-on: ${{ matrix.os }}
    steps:
      - run: dotnet publish
