name: test-actions
run-name: ${{ github.actor }} is trying to write his first Action
on: 
  push:
  pull_request:
    branches:
      - main
jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  build:
    runs-on: ubuntu-latest
    needs: print-hello
    steps:
      - run: dotnet restore Actions-Kata.sln
      - run: dotnet build Actions-Kata.sln
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: dotnet test Actions-Kata.sln
  publish: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: dotnet publish Actions-Kata.sln
